INSERT INTO BOOK (ID, AUTHOR, ISBN, PUBLISH_DATE, TITLE) VALUES (1, 'TEST AUTHOR1', 'TESTISBN', '2001-01-01', 'TEST TITLE 1');
INSERT INTO BOOK (ID, AUTHOR, ISBN, PUBLISH_DATE, TITLE) VALUES (2, 'TEST AUTHOR2', 'TESTISBN2', '2001-01-01', 'TEST TITLE 2');
INSERT INTO BOOK (ID, AUTHOR, ISBN, PUBLISH_DATE, TITLE) VALUES (3, 'TEST AUTHOR3', 'TESTISBN3', '2001-01-01', 'TEST TITLE 3');